FROM node:16

EXPOSE 5000

WORKDIR /usr/src/app

COPY . .

ENV REACT_APP_BACKEND_URL=http://localhost:8080

RUN npm install && \ 
    npm run build && \
    npm install -g serve && \
    useradd -m appuser && \
    chown appuser .

# change user
USER appuser

# Serve app
CMD ["serve", "-s", "-l", "5000", "build"]
