version: "3"

services:

  back:
    image: back-project
    build: ./example-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - REQUEST_ORIGIN=http://localhost

  front:
    image: front-project
    build: ./example-frontend
    ports:
      - 5000:5000
    environment:
      REACT_APP_BACKEND_URL: http://localhost:80/api/

  redis:
    image: redis:7
    ports:
      - 6379:6379

  postgres:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  nginx:
    image: nginx:1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
