version: "3"
services:
  back:
    image: back-project
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
  front:
    image: front-project
    ports:
      - 5000:5000
  redis:
    image: redis:7
    ports:
      - 6379:6379
